name: Build Windows .pyz
permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13"]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Setup Python virtual environment
        run: |
          uv venv --python ${{ matrix.python-version }} &&
          .venv\Scripts\activate
          echo "VIRTUAL_ENV=$PWD/.venv" >> $GITHUB_ENV &&
          echo "$PWD/.venv/bin" >> $GITHUB_PATH

      - name: Install Python dependencies
        run: |
          uv sync --active --group standalone-executable-builders

      - name: Build self contained Python zipapp
        run: |
          .venv\Scripts\activate &&
          shiv -e "blonder_tinkham_klapwijk_model.main:main" -o btk_win32.pyz --compressed .

      - uses: actions/upload-artifact@v4
        with:
          name: btk_win32.pyz
          path: btk_win32.pyz
